<?php
session_start(); if(!isset($_SESSION['admin'])){header('Location:login.php');exit;}
$dataFile=__DIR__.'/../data/site.json';$data=json_decode(file_get_contents($dataFile),true);$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(isset($_POST['save_site'])){foreach(['business_name','headline','tagline','about','phone','whatsapp','email','address','instagram','facebook'] as $k)$data[$k]=trim($_POST[$k]??'');file_put_contents($dataFile,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX);$msg='Website details saved.';}
 if(isset($_POST['save_services'])){$sv=[];$titles=$_POST['service_title']??[];$icons=$_POST['service_icon']??[];$texts=$_POST['service_text']??[];for($i=0;$i<count($titles);$i++)if(trim($titles[$i])!=='')$sv[]=['icon'=>$icons[$i]??'✨','title'=>trim($titles[$i]),'text'=>trim($texts[$i]??'')];$data['services']=$sv;file_put_contents($dataFile,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX);$msg='Services saved.';}
 if(isset($_POST['upload'])&&!empty($_FILES['photo']['name'])&&$_FILES['photo']['error']===UPLOAD_ERR_OK){$ext=strtolower(pathinfo($_FILES['photo']['name'],PATHINFO_EXTENSION));$ok=['jpg','jpeg','png','webp','gif'];if(in_array($ext,$ok,true)&&$_FILES['photo']['size']<=8*1024*1024){$name=date('Ymd_His').'_'.bin2hex(random_bytes(3)).'.'.$ext;move_uploaded_file($_FILES['photo']['tmp_name'],__DIR__.'/../uploads/'.$name);$data['gallery'][]=['file'=>$name,'title'=>trim($_POST['photo_title']??'Our Work')];file_put_contents($dataFile,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX);$msg='Photo uploaded.';}else{$msg='Use JPG, PNG, WEBP or GIF up to 8 MB.';}}
 if(isset($_POST['delete'])){$i=(int)$_POST['idx'];if(isset($data['gallery'][$i])){@unlink(__DIR__.'/../uploads/'.$data['gallery'][$i]['file']);array_splice($data['gallery'],$i,1);file_put_contents($dataFile,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX);$msg='Photo deleted.';}}
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sakthi Admin</title><link rel="stylesheet" href="admin.css"></head><body>
<header><b>Sakthi Admin</b><div><a href="../" target="_blank">View Website</a><a href="logout.php">Logout</a></div></header><main>
<?php if($msg): ?><div class="msg"><?=htmlspecialchars($msg)?></div><?php endif; ?>
<form method="post"><section><h2>Business Details</h2><div class="grid">
<label>Business Name<input name="business_name" value="<?=htmlspecialchars($data['business_name'])?>"></label><label>Headline<input name="headline" value="<?=htmlspecialchars($data['headline'])?>"></label>
<label>Phone<input name="phone" value="<?=htmlspecialchars($data['phone'])?>"></label><label>WhatsApp<input name="whatsapp" value="<?=htmlspecialchars($data['whatsapp'])?>"></label>
<label>Email<input name="email" value="<?=htmlspecialchars($data['email'])?>"></label><label>Instagram URL<input name="instagram" value="<?=htmlspecialchars($data['instagram'])?>"></label>
<label>Facebook URL<input name="facebook" value="<?=htmlspecialchars($data['facebook'])?>"></label><label class="full">Address<textarea name="address"><?=htmlspecialchars($data['address'])?></textarea></label>
<label class="full">Tagline<textarea name="tagline"><?=htmlspecialchars($data['tagline'])?></textarea></label><label class="full">About<textarea name="about"><?=htmlspecialchars($data['about'])?></textarea></label>
</div><button name="save_site">Save Website Details</button></section></form>
<form method="post"><section><h2>Services</h2><?php foreach(($data['services']??[]) as $s): ?><div class="service-row"><input name="service_icon[]" value="<?=htmlspecialchars($s['icon'])?>"><input name="service_title[]" value="<?=htmlspecialchars($s['title'])?>"><input name="service_text[]" value="<?=htmlspecialchars($s['text'])?>"></div><?php endforeach; ?><div class="service-row"><input name="service_icon[]" placeholder="✨"><input name="service_title[]" placeholder="New service"><input name="service_text[]" placeholder="Description"></div><button name="save_services">Save Services</button></section></form>
<section><h2>Gallery — Upload Photos Anytime</h2><form method="post" enctype="multipart/form-data"><div class="upload"><input type="file" name="photo" accept="image/*" required><input name="photo_title" placeholder="Photo title"><button name="upload">Upload Photo</button></div><small>JPG / PNG / WEBP / GIF • max 8 MB</small></form>
<div class="gallery"><?php foreach(($data['gallery']??[]) as $i=>$g): ?><div class="g"><img src="../uploads/<?=htmlspecialchars($g['file'])?>"><b><?=htmlspecialchars($g['title'])?></b><form method="post"><input type="hidden" name="idx" value="<?=$i?>"><button name="delete" class="danger">Delete</button></form></div><?php endforeach; ?></div></section>
</main></body></html>